-- Baseline schema for TalentGrid.
-- Existing databases are baselined at this version by Flyway (not executed).
-- Fresh installs run this to create every base table.

CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version          BIGINT NOT NULL DEFAULT 0,
    full_name        VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL UNIQUE,
    phone            VARCHAR(255) NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    role             VARCHAR(255) NOT NULL,
    status           VARCHAR(255) NOT NULL DEFAULT 'UNDER_REVIEW',
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    headline         VARCHAR(255),
    city             VARCHAR(255),
    total_exp        INTEGER,
    about            TEXT,
    resume_file      VARCHAR(255),
    profile_strength INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT users_role_check   CHECK (role IN ('CANDIDATE','ADMIN','EMPLOYER'))
);

CREATE TABLE user_skills (
    user_id BIGINT NOT NULL REFERENCES users(id),
    skill   VARCHAR(255)
);

CREATE TABLE user_experience (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    title       VARCHAR(255) NOT NULL,
    company     VARCHAR(255) NOT NULL,
    location    VARCHAR(255),
    start_date  DATE,
    end_date    DATE,
    current     BOOLEAN NOT NULL,
    description TEXT
);

CREATE TABLE user_education (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id),
    institution    VARCHAR(255) NOT NULL,
    degree         VARCHAR(255),
    field_of_study VARCHAR(255),
    start_year     INTEGER,
    end_year       INTEGER,
    grade          VARCHAR(255)
);

CREATE TABLE jobs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT NOT NULL DEFAULT 0,
    title                 VARCHAR(255) NOT NULL,
    company               VARCHAR(255) NOT NULL,
    company_logo_initials VARCHAR(255),
    location              VARCHAR(255) NOT NULL,
    category              VARCHAR(255) NOT NULL,
    employment_type       VARCHAR(255) NOT NULL,
    experience_min        INTEGER,
    experience_max        INTEGER,
    salary_min            INTEGER,
    salary_max            INTEGER,
    openings              INTEGER,
    description           TEXT,
    education             VARCHAR(255),
    about_company         TEXT,
    posted_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    active                BOOLEAN NOT NULL DEFAULT TRUE,
    posted_by             BIGINT REFERENCES users(id)
);

CREATE TABLE job_skills (
    job_id BIGINT NOT NULL REFERENCES jobs(id),
    skill  VARCHAR(255)
);

CREATE TABLE job_responsibilities (
    job_id         BIGINT NOT NULL REFERENCES jobs(id),
    responsibility TEXT
);

CREATE TABLE job_requirements (
    job_id      BIGINT NOT NULL REFERENCES jobs(id),
    requirement TEXT
);

CREATE TABLE applications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT NOT NULL DEFAULT 0,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    job_id       BIGINT NOT NULL REFERENCES jobs(id),
    status       VARCHAR(255) NOT NULL,
    cover_letter TEXT,
    resume_url   VARCHAR(255),
    applied_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT applications_status_check CHECK (status IN ('APPLIED','SHORTLISTED','REJECTED')),
    CONSTRAINT applications_user_job_unique UNIQUE (user_id, job_id)
);
