ALTER TABLE users ADD COLUMN photo_file VARCHAR(255);

CREATE TABLE saved_jobs (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES users(id),
    job_id   BIGINT NOT NULL REFERENCES jobs(id),
    saved_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT saved_jobs_user_job_unique UNIQUE (user_id, job_id)
);
CREATE INDEX idx_saved_jobs_user ON saved_jobs(user_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    type       VARCHAR(40) NOT NULL,
    message    TEXT NOT NULL,
    link       VARCHAR(255),
    read       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC);

CREATE TABLE subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version    BIGINT NOT NULL DEFAULT 0,
    user_id    BIGINT NOT NULL UNIQUE REFERENCES users(id),
    plan       VARCHAR(20) NOT NULL DEFAULT 'FREE',
    expires_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT subscriptions_plan_check CHECK (plan IN ('FREE','PRO'))
);
