-- Normalise existing names: collapse whitespace and title-case each word.
UPDATE users SET full_name = initcap(regexp_replace(trim(full_name), '\s+', ' ', 'g'));

CREATE TABLE insights (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT NOT NULL DEFAULT 0,
    slug         VARCHAR(160) NOT NULL UNIQUE,
    title        VARCHAR(255) NOT NULL,
    category     VARCHAR(80)  NOT NULL,
    read_time    VARCHAR(30)  NOT NULL,
    excerpt      TEXT NOT NULL,
    body         TEXT NOT NULL,
    published    BOOLEAN NOT NULL DEFAULT TRUE,
    published_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_insights_published ON insights(published, published_at DESC);
