CREATE TABLE companies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT NOT NULL DEFAULT 0,
    owner_id      BIGINT NOT NULL UNIQUE REFERENCES users(id),
    name          VARCHAR(200) NOT NULL,
    logo_initials VARCHAR(10),
    website       VARCHAR(255),
    industry      VARCHAR(80),
    size          VARCHAR(40),
    city          VARCHAR(120),
    description   TEXT,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

ALTER TABLE jobs ADD COLUMN company_id BIGINT REFERENCES companies(id);
CREATE INDEX idx_jobs_company_id ON jobs(company_id);
