-- Recruiters can mark an application as being reviewed before deciding.
ALTER TABLE applications DROP CONSTRAINT IF EXISTS applications_status_check;
ALTER TABLE applications ADD CONSTRAINT applications_status_check
    CHECK (status IN ('APPLIED','UNDER_REVIEW','SHORTLISTED','REJECTED'));

-- One row per stage an application has reached, so candidates see a dated timeline.
CREATE TABLE application_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(id),
    status         VARCHAR(20) NOT NULL,
    note           VARCHAR(255),
    changed_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT application_status_history_status_check
        CHECK (status IN ('APPLIED','UNDER_REVIEW','SHORTLISTED','REJECTED'))
);
CREATE INDEX idx_application_status_history_app
    ON application_status_history(application_id, changed_at);

-- Backfill: every existing application starts with an APPLIED entry, plus its
-- current stage when it has already moved on. Both use applied_at, because the
-- original change time was never recorded.
INSERT INTO application_status_history (application_id, status, note, changed_at)
SELECT id, 'APPLIED', 'Application submitted', applied_at FROM applications;

INSERT INTO application_status_history (application_id, status, note, changed_at)
SELECT id, status, 'Recorded before status history was tracked', applied_at
FROM applications WHERE status <> 'APPLIED';
